### ISSUE TITLE
Trim the whitespace characters

### ISSUE THREAD

**Issue by coooolers** [o15y/staart#113]
For instance, Settings > Name  Just Enter the whitespace characters and it allows them.

I believe we need to trim almost every input field.

**Comment by coooolers** [comment]
I think we should not allow the HTML tags while entering any kind of input. It could probably  lead to XSS security attacks.

**Comment by AnandChowdhary** [comment]
Hopefully this shouldn't be the case because Vue handles XSS for us (both `{{ variable }}` and `v-model` take care of preventing `<`s, but perhaps I can also escape them when storing in the database. I'm not sure whether this is the best way forward, though, because there may be use cases (like HTML email forms, etc.) where we want people to be able to input Markdown/HTML and store that.

**Comment by AnandChowdhary** [comment]
Turns out we're already trimming strings: https://github.com/o15y/staart/blob/master/src/helpers/mysql.ts#L103

Some forms in Staart UI don't update state after saving, so that's probably why the space character remains in an input, though it's not stored in the database. I'll update UI to fix that.
