### ISSUE TITLE
Feature: Trial Period and Days Left

### ISSUE THREAD

**Issue by coooolers** [o15y/staart#168]
Hi

Looks like the work is in progress. Good job!

I believe an important feature is missing, There should be a flag in config file, namely, Trial Period. Let us say, we set it to 15 days. So the app should be accessible for free for that period.

Also, the system should notify (by email and instant notification both) that your subscription is about to expire in DAYS_LEFT time.

Thanks

**Comment by AnandChowdhary** [comment]
Hi @coooolers, thanks for opening this issue!

Trial period and days left are already supported, but you have to configure them through Stripe. Log in to your Stripe account, create a product, and add pricing plans. You can then configure a trial period, rate, etc. Since Staart relies upon Stripe for billing and subscriptions, it would be unnecessary to add this as a feature within Staart.

As you'd see in the demo, the info about plans, prices, trials, etc., come from Stripe through the Staart REST API:

![Screenshot of subscriptions plans](https://user-images.githubusercontent.com/2841780/62102226-cf677780-b2b5-11e9-97cf-1960bdaadb02.png)

**Comment by coooolers** [comment]
Okay thanks for the information.
